workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        PACKAGE_NAME: "io.codemagic.sample.androidnative"
      android_signing:
        - keystore: $ANDROID_KEYSTORE
          keystore_password: "Farofadenescau123@"
          key_alias: "my-key-alias"
          key_password: "Farofadenescau123@"

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Android release
        script: |
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
